export  const RC = {
    PREFIX_API : `/api`,
    LIST_FEATURES : `/lfe`,
    LISTNEWS  : `/ln`,
    LISTMOSTVIEW : `/lmv`,
    LISTCHUDE : `/lcd`,
    LISTTOPICAL : `/ltp`,
    LOADMORETOPIC : `/lmtp`,
    TOPICALDETAIL :  `/lcdt`,
    LOADMOREHOME : `/lmh`,
    LOADMORENEWSPAPER : `/lmns`,
    LOADDETAILNEWSPAPER: `/ldnsp`,
    LISTNEWSPAPER : `/lns`,
    LISTCAT : `/lc`,
    CATEAPI : `/ca`,
    ARTICLEDETAIL : `/detail`,
    LISTTAG : `/tag`,
    LOADMORETAG : `/lmt`, 
    LISTTHEME : `/theme`,
    LOADMORETHEME : `/theme`,
    TOPICALHIGHLIGHT: `/th`,
    AUTHOR : `/author`,
    LOGIN: `/login`,
    RG :  `/register`,
    SENDCOMMENT : `/sc`,
    LISTCOMMENT : `/listcmt`,
    REPORTCOMMENT:`/rpcmt`,
    LIKECOMMENT:`/lcmt`,
    LIST_RELATED:`/lrl`,
};