const FETCH_LIST_ROLE = 'FETCH_LIST_ROLE';
const FETCH_LIST_ROLE_SUCCESS = 'FETCH_LIST_ROLE_SUCCESS';
const FETCH_LIST_ROLE_FAILED = 'FETCH_LIST_ROLE_FAILED';
export {
    FETCH_LIST_ROLE,
    FETCH_LIST_ROLE_SUCCESS,
    FETCH_LIST_ROLE_FAILED,
};
