const FETCH_LIST_USER_BASE = 'FETCH_USER_BASE';
const FETCH_LIST_USER_BASE_SUCCESS = 'FETCH_USER_BASE_SUCCESS';
const FETCH_LIST_USER_BASE_FAILED = 'FETCH_USER_BASE_FAILED';

const DELETE_USER_BASE ="DELETE_USER_BASE";
const DELETE_USER_BASE_SUCCESS = "DELETE_USER_BASE_SUCCESS";
const DELETE_USER_BASE_FAILED = "DELETE_USER_BASE_FAILED";

const ADD_USER_BASE = "ADD_USER_BASE";
const ADD_USER_BASE_SUCCESS = "ADD_USER_BASE_SUCCESS";
const ADD_USER_BASE_FAILED = "ADD_USER_BASE_FAILED";

const EDIT_USER_BASE = "EDIT_USER_BASE";
const EDIT_USER_BASE_SUCCESS = "EDIT_USER_BASE_SUCCESS";
const EDIT_USER_BASE_FAILED = "EDIT_USER_BASE_FAILED";
export {
    FETCH_LIST_USER_BASE,
    FETCH_LIST_USER_BASE_SUCCESS,
    FETCH_LIST_USER_BASE_FAILED,
    DELETE_USER_BASE,
    DELETE_USER_BASE_SUCCESS,
    DELETE_USER_BASE_FAILED,
    ADD_USER_BASE,
    ADD_USER_BASE_SUCCESS,
    ADD_USER_BASE_FAILED,
    EDIT_USER_BASE,
    EDIT_USER_BASE_SUCCESS,
    EDIT_USER_BASE_FAILED
}
