export const FETCH_LIST_USER_DEGREE = 'FETCH_USER_DEGREE';
export const FETCH_LIST_USER_DEGREE_SUCCESS = 'FETCH_USER_DEGREE_SUCCESS';
export const FETCH_LIST_USER_DEGREE_FAILED = 'FETCH_USER_DEGREE_FAILED';

export const DELETE_USER_DEGREE ="DELETE_USER_DEGREE";
export const DELETE_USER_DEGREE_SUCCESS = "DELETE_USER_DEGREE_SUCCESS";
export const DELETE_USER_DEGREE_FAILED = "DELETE_USER_DEGREE_FAILED";

export const ADD_USER_DEGREE = "ADD_USER_DEGREE";
export const ADD_USER_DEGREE_SUCCESS = "ADD_USER_DEGREE_SUCCESS";
export const ADD_USER_DEGREE_FAILED = "ADD_USER_DEGREE_FAILED";

export const EDIT_USER_DEGREE = "EDIT_USER_DEGREE";