export const FETCH_LIST_USER_DEPARTMENT = 'FETCH_LIST_USER_DEPARTMENT';
export const FETCH_LIST_USER_DEPARTMENT_SUCCESS = 'FETCH_LIST_USER_DEPARTMENT_SUCCESS';
export const FETCH_LIST_USER_DEPARTMENT_FAILED = 'FETCH_LIST_USER_DEPARTMENT_FAILED';

export const DELETE_USER_DEPARTMENT ="DELETE_USER_DEPARTMENT";
export const DELETE_USER_DEPARTMENT_SUCCESS = "DELETE_USER_DEPARTMENT_SUCCESS";
export const DELETE_USER_DEPARTMENT_FAILED = "DELETE_USER_DEPARTMENT_FAILED";

export const ADD_USER_DEPARTMENT = "ADD_USER_DEPARTMENT";
export const ADD_USER_DEPARTMENT_SUCCESS = "ADD_USER_DEPARTMENT_SUCCESS";
export const ADD_USER_DEPARTMENT_FAILED = "ADD_USER_DEPARTMENT_FAILED";

export const EDIT_USER_DEPARTMENT = "EDIT_USER_DEPARTMENT";