export const FETCH_LIST_USER_WORK_OBJECT = 'FETCH_USER_WORK_OBJECT';
export const FETCH_LIST_USER_WORK_OBJECT_SUCCESS = 'FETCH_USER_WORK_OBJECT_SUCCESS';
export const FETCH_LIST_USER_WORK_OBJECT_FAILED = 'FETCH_USER_WORK_OBJECT_FAILED';

export const DELETE_USER_WORK_OBJECT ="DELETE_USER_WORK_OBJECT";
export const DELETE_USER_WORK_OBJECT_SUCCESS = "DELETE_USER_WORK_OBJECT_SUCCESS";
export const DELETE_USER_WORK_OBJECT_FAILED = "DELETE_USER_WORK_OBJECT_FAILED";

export const ADD_USER_WORK_OBJECT = "ADD_USER_WORK_OBJECT";
export const ADD_USER_WORK_OBJECT_SUCCESS = "ADD_USER_WORK_OBJECT_SUCCESS";
export const ADD_USER_WORK_OBJECT_FAILED = "ADD_USER_WORK_OBJECT_FAILED";

export const EDIT_USER_WORK_OBJECT = "EDIT_USER_WORK_OBJECT";