export const FETCH_LIST_USER_JOURNALIST_CARD = 'FETCH_USER_JOURNALIST_CARD';
export const FETCH_LIST_USER_JOURNALIST_CARD_SUCCESS = 'FETCH_USER_JOURNALIST_CARD_SUCCESS';
export const FETCH_LIST_USER_JOURNALIST_CARD_FAILED = 'FETCH_USER_JOURNALIST_CARD_FAILED';

export const DELETE_USER_JOURNALIST_CARD ="DELETE_USER_JOURNALIST_CARD";
export const DELETE_USER_JOURNALIST_CARD_SUCCESS = "DELETE_USER_JOURNALIST_CARD_SUCCESS";
export const DELETE_USER_JOURNALIST_CARD_FAILED = "DELETE_USER_JOURNALIST_CARD_FAILED";

export const ADD_USER_JOURNALIST_CARD = "ADD_USER_JOURNALIST_CARD";
export const ADD_USER_JOURNALIST_CARD_SUCCESS = "ADD_USER_JOURNALIST_CARD_SUCCESS";
export const ADD_USER_JOURNALIST_CARD_FAILED = "ADD_USER_JOURNALIST_CARD_FAILED";

export const EDIT_USER_JOURNALIST_CARD = "EDIT_USER_JOURNALIST_CARD";