export const FETCH_LIST_USER_SIX = 'FETCH_USER_SIX';
export const FETCH_LIST_USER_SIX_SUCCESS = 'FETCH_USER_SIX_SUCCESS';
export const FETCH_LIST_USER_SIX_FAILED = 'FETCH_USER_SIX_FAILED';

export const DELETE_USER_SIX ="DELETE_USER_SIX";
export const DELETE_USER_SIX_SUCCESS = "DELETE_USER_SIX_SUCCESS";
export const DELETE_USER_SIX_FAILED = "DELETE_USER_SIX_FAILED";

export const ADD_USER_SIX = "ADD_USER_SIX";
export const ADD_USER_SIX_SUCCESS = "ADD_USER_SIX_SUCCESS";
export const ADD_USER_SIX_FAILED = "ADD_USER_SIX_FAILED";

export const EDIT_USER_SIX = "EDIT_USER_SIX";
export const EDIT_USER_SIX_SUCCESS = "EDIT_USER_SIX_SUCCESS";
export const EDIT_USER_SIX_FAILED = "EDIT_USER_SIX_FAILED";