export const FETCH_LIST_USER_PERSONAL_HISTORY = 'FETCH_USER_PERSONAL_HISTORY';
export const FETCH_LIST_USER_PERSONAL_HISTORY_SUCCESS = 'FETCH_USER_PERSONAL_HISTORY_SUCCESS';
export const FETCH_LIST_USER_PERSONAL_HISTORY_FAILED = 'FETCH_USER_PERSONAL_HISTORY_FAILED';

export const DELETE_USER_PERSONAL_HISTORY ="DELETE_USER_PERSONAL_HISTORY";
export const DELETE_USER_PERSONAL_HISTORY_SUCCESS = "DELETE_USER_PERSONAL_HISTORY_SUCCESS";
export const DELETE_USER_PERSONAL_HISTORY_FAILED = "DELETE_USER_PERSONAL_HISTORY_FAILED";

export const ADD_USER_PERSONAL_HISTORY = "ADD_USER_PERSONAL_HISTORY";
export const ADD_USER_PERSONAL_HISTORY_SUCCESS = "ADD_USER_PERSONAL_HISTORY_SUCCESS";
export const ADD_USER_PERSONAL_HISTORY_FAILED = "ADD_USER_PERSONAL_HISTORY_FAILED";

export const EDIT_USER_PERSONAL_HISTORY = "EDIT_USER_PERSONAL_HISTORY";