export const FETCH_LIST_USER_BASE = 'FETCH_USER_BASE';
export const FETCH_LIST_USER_BASE_SUCCESS = 'FETCH_USER_BASE_SUCCESS';
export const FETCH_LIST_USER_BASE_FAILED = 'FETCH_USER_BASE_FAILED';

export const DELETE_USER_BASE ="DELETE_USER_BASE";
export const DELETE_USER_BASE_SUCCESS = "DELETE_USER_BASE_SUCCESS";
export const DELETE_USER_BASE_FAILED = "DELETE_USER_BASE_FAILED";

export const ADD_USER_BASE = "ADD_USER_BASE";
export const ADD_USER_BASE_SUCCESS = "ADD_USER_BASE_SUCCESS";
export const ADD_USER_BASE_FAILED = "ADD_USER_BASE_FAILED";

export const EDIT_USER_BASE = "EDIT_USER_BASE";
export const EDIT_USER_BASE_SUCCESS = "EDIT_USER_BASE_SUCCESS";
export const EDIT_USER_BASE_FAILED = "EDIT_USER_BASE_FAILED";